port: 9999 #端口号
mysqlUrl: "root:root@tcp(192.168.101.90:3306)/t_gorm?charset=utf8mb4&parseTime=True&loc=Local" #数据库链接
#   - "/*" 排除所有   - "/admin/*" 排除admin下所有
excludePath:
  - "/"
  - "/admin/login"
  - "/admin/*" #排除admin下所有用于测试 flutter 后台
  - "/file/upload"
  - "/favicon.ico" #排除ico文件
#文件上传路径
uploadPath: "D:\\nginx-1.22.1\\files\\image\\"
#文件访问路径
uploadUrl: "http://192.168.101.100:88/image/"
